### ISSUE TITLE
[FE] 리팩토링 셋팅 (한달통계, 색구매)

### ISSUE THREAD

**Issue by YeryunJung** [codestates-seb/seb40_main_029#126]
### Description 
목업 데이터와 한달통계, 색구매 모달 연결

### To-do
- [x] data.json colorCode 추가
- [x] data.json palette 추가
- [x] 한달통계, 색구매 데이터 연결
