### ISSUE TITLE
[FE] refactor/mood,todo,lookback

### ISSUE THREAD

**Issue by kosmos992** [codestates-seb/seb40_main_029#129]
### Description 
세가지 모듈의 리팩토링 및 반응형 적용

### To-do
- [x] 무드셀렉터 코드 정리
- [x] 투두리스트 코드 정리
- [x] 연간기록 코드 정리
- [x] 반응형 적용
