### ISSUE TITLE
[FE] 리팩토링 (색상테마, 한달통계)

### ISSUE THREAD

**Issue by YeryunJung** [codestates-seb/seb40_main_029#131]
### Description 
색상테마, 한달 통계 코드 리팩토링

### To-do
- [x] import 순서 변경
- [x] 변수명 수정
- [x] 분기처리 확인
- [x] 불필요한 state, useEffect 제거
- [x] 의미없는 console.log, import 제거
