### ISSUE TITLE
[FE] refactor/bookmark

### ISSUE THREAD

**Issue by Ko-Eunseo** [codestates-seb/seb40_main_029#133]
### Description 
사용성 개선
버그픽스

### To-do
- [x] 북마크 url 유효성 검사
- [x] 툴팁 추가
- [x] url + 이름 둘다 있어야 버튼 활성화
- [x] 버튼 내용 길어질시 ellipsis 적용
- [x] 북마크 같은이름일때 둘다 삭제되는 버그
