### ISSUE TITLE
[FE] 홈 헤더로 로그인 버튼 이전

### ISSUE THREAD

**Issue by YeryunJung** [codestates-seb/seb40_main_029#138]
### Description 
첫 화면에 바로 로그인 버튼이 보여졌던 것을 홈화면의 헤더에서 로그인 할 수 있게 변경

### To-do
- [x] 헤더로 버튼 이전
- [x] 클릭시 로그인 연결 확인
- [x] 로그아웃 상태일 때 토스트 알림
