### ISSUE TITLE
[FE] react query 도입 추진

### ISSUE THREAD

**Issue by Ko-Eunseo** [codestates-seb/seb40_main_029#182]
### Description 
1. 도입 사유
* 각각 다른 모달에서 다수의 같은 fetch를 하고있다는 것을 발견
* client state 와 server state를 분리해서 관리해야 할 필요성을 느낌
* refresh + useEffect의 조합이 좋은 방법은 아니라는 것을 깨달음

### To-do
- [ ] tanstack query 설치(리액트쿼리 최신스택)
- [ ] refresh + useEffect 없애기
- [ ] 서버 상태 분리해 관리하기

**Comment by Ko-Eunseo** [comment]
hotfix: friend
- [ ] friend get 에러
- [ ] friend post 에러
